apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: netomedia-deployment
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: netomedia-deployment
  targetCPUUtilizationPercentage: 50
