apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-06-11T08:02:43Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: netomedia-test
  name: netomedia-deployment
  namespace: default
  resourceVersion: "295467"
  selfLink: /api/v1/namespaces/default/services/netomedia-deployment
  uid: ee9f9685-725f-4464-9935-d5421fa203cd
spec:
  clusterIP: 10.28.7.109
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31549
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: netomedia-test
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.72.142.233
